config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy] do
  end

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post:confirm
    end
  end
  resources :contacts, only: [:index, :new, :create] do
    collection do
      post:confirm
    end
  end

  resources :poems, only: [:index,:show]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  
  # configure_permitted_parametersという専用のストロングパラメータを設定するメソッドを使用して、
  # nameカラムが新規登録とアカウント更新の際に、パラメータに含まれるようにする。
  
  # before_actionで下で定義したメソッドを実行　# deviseのControllerの場合のみ起動
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name)
  
  protected
  # protected クラス外から呼び出すことができる

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end

  #画像アップロード用
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)
  #PERMISSIBLE_ATTRIBUTES = %i(name img img_cache)

  private
    #画像アップロード用
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # プロフィールイメージ
    def profile_img(user)
        # アップロードした画像用
        return image_tag(user.avatar, alt: user.name, class: "mod-profile-img") if user.avatar?

        # SNSから引き継いだ画像用
        unless user.provider.blank?
          img_url = user.image_url
        else
          img_url = 'no_image.png'
        end
        image_tag(img_url, alt: user.name, class: "mod-profile-img")
    end

    def application_user_admin_flag()
        current_user.admin
    end

end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/views/application/_picture_list.html.erb
<% @pictures.each do |picture| %>
    <div class="panel panel-default">
        <div class="panel-body">
            <h4 class="text-left"><strong><%= picture.title %></strong></h4>
            <% if picture.img %>
                <p><%= image_tag(picture.img,class:"test") %></p>
            <% end %>
            <p class="text-left"><%= picture.content %></p>
            <hr>
            <p class="text-left">書いた人:<%= picture.user.name %></p>
            <p class="text-left">プロフィール画像: <%= profile_img(picture.user) %></p>
            <hr>
            <p>
                <%= link_to "編集", edit_picture_path(picture.id), class: 'btn btn-default' %>
                <%= link_to "削除", picture_path(picture), method: :delete, data: {confirm:'本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
            </p>
        </div>
    </div>
<% end %>