config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy] do
  end

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post:confirm
    end
  end
  resources :contacts, only: [:index, :new, :create] do
    collection do
      post:confirm
    end
  end

  resources :poems, only: [:index,:show]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Insta</title>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0"><!--スマホ対応ある場合-->
	<!-- <link rel="canonical" href=""> -->
<!-- 	<link rel="icon" href="/icon/favicon.ico">
	<link rel="apple-touch-icon" href="/icon/icon.png">
	<link rel="alternate" type="application/rss+xml" href=""> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Insta", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "＋", new_picture_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ', edit_user_registration_path %></li>
              <% if application_user_admin_flag %>
                <li><%= link_to '管理画面', rails_admin_path %></li>
              <% end %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path  %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>
<%= yield %>

  <footer>
    <p>© 2015-2016 Copyright Insta.</p>
  </footer>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>